export const ADD_INGRIDIENT= 'ADD_INGRIDIENT'
export const REMOVE_INGRIDIENT= 'REMOVE_INGRIDIENT'
export const GET_INGRIDIENT= 'GET_INGRIDIENT'
export const FETCH_INGRIDIENTS_FAILED='FETCH_INGRIDIENTS_FAILED'

export const POST_ORDER_FAILED= 'POST_ORDER_FAILED'
export const POST_ORDER_SUCCESS= 'POST_ORDER_SUCCESS'
export const POST_ORDERS_START= 'POST_ORDERS_START'
export const PURCHASE_INIT= 'PURCHASE_INIT'
export const FETCH_ORDERS= 'FETCH_ORDERS'
export const FETCH_ORDER_SUCCESS= 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAILED= 'FETCH_ORDER_FAILED'

export const AUTH_START= 'AUTH_START'
export const AUTH_SUCCESS= 'AUTH_SUCCESS'
export const AUTH_FAILED= 'AUTH_FAILED'
export const AUTH_LOGOUT= 'AUTH_LOGOUT'



